### ISSUE TITLE
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :    namespace ‘processx’ 3.4.3 is being loaded, but >= 3.5.0 is required

### ISSUE THREAD

**Issue by Edson050788** [FinYang/tsdl#5]
I am using Microsoft R Open ver. 4.0 64-bit, i find the error titled above when typing the command: devtools::install_github("FinYang/tsdl")

**Comment by robjhyndman** [comment]
As the error says, your processx package is out-of-date. Update it and try again.
